-- Create Skills Table
CREATE TABLE IF NOT EXISTS public.skills (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create UserSkills junction table
CREATE TABLE IF NOT EXISTS public.user_skills (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES public.skills (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, skill_id)
);

CREATE INDEX IF NOT EXISTS idx_user_skills_user_id ON public.user_skills (user_id);

CREATE INDEX IF NOT EXISTS idx_user_skills_skill_id ON public.user_skills (skill_id);

-- Insert common tech skills
INSERT INTO
    public.skills (name)
VALUES
    -- Programming Languages
    ('JavaScript'),
    ('Python'),
    ('Java'),
    ('C++'),
    ('C'),
    ('C#'),
    ('TypeScript'),
    ('Go'),
    ('Rust'),
    ('Ruby'),
    ('PHP'),
    ('Swift'),
    ('Kotlin'),
    ('Dart'),
    ('Scala'),
    ('R'),
    ('MATLAB'),
    ('Perl'),
    ('Shell'),
    ('Bash'),

-- Web Development
('HTML'),
('CSS'),
('React'),
('Angular'),
('Vue.js'),
('Node.js'),
('Express.js'),
('Django'),
('Flask'),
('Spring Boot'),
('ASP.NET'),
('Laravel'),
('Next.js'),
('Nuxt.js'),
('Svelte'),
('jQuery'),
('Bootstrap'),
('Tailwind CSS'),
('SASS'),
('LESS'),
('Webpack'),
('Vite'),

-- Mobile Development
('React Native'),
('Flutter'),
('Android'),
('iOS'),
('Xamarin'),
('Ionic'),

-- Databases
('MySQL'),
('PostgreSQL'),
('MongoDB'),
('SQLite'),
('Redis'),
('Oracle'),
('SQL Server'),
('MariaDB'),
('Cassandra'),
('DynamoDB'),
('Firebase'),
('Supabase'),
('Firestore'),
('CouchDB'),

-- Cloud & DevOps
('AWS'),
('Azure'),
('Google Cloud'),
('GCP'),
('Docker'),
('Kubernetes'),
('Jenkins'),
('CI/CD'),
('Terraform'),
('Ansible'),
('GitHub Actions'),
('GitLab CI'),
('CircleCI'),
('Heroku'),
('Vercel'),
('Netlify'),
('DigitalOcean'),

-- Data Science & ML
('Machine Learning'),
('Deep Learning'),
('TensorFlow'),
('PyTorch'),
('Keras'),
('Scikit-learn'),
('Pandas'),
('NumPy'),
('Matplotlib'),
('Seaborn'),
('Data Analysis'),
('Data Visualization'),
('Natural Language Processing'),
('NLP'),
('Computer Vision'),
('OpenCV'),

-- Tools & Platforms
('Git'),
('GitHub'),
('GitLab'),
('Bitbucket'),
('VS Code'),
('IntelliJ IDEA'),
('Eclipse'),
('Postman'),
('Insomnia'),
('Jira'),
('Trello'),
('Slack'),
('Figma'),
('Adobe XD'),
('Photoshop'),

-- Testing
('Jest'),
('Mocha'),
('Chai'),
('Selenium'),
('Cypress'),
('Pytest'),
('JUnit'),
('TestNG'),
('Unit Testing'),
('Integration Testing'),
('E2E Testing'),

-- Other Technologies
('REST API'),
('GraphQL'),
('WebSocket'),
('gRPC'),
('Microservices'),
('OAuth'),
('JWT'),
('Blockchain'),
('Solidity'),
('Ethereum'),
('Web3'),
('API Development'),
('System Design'),
('Data Structures'),
('Algorithms'),
('OOP'),
('Functional Programming'),
('Agile'),
('Scrum'),
('Linux'),
('Ubuntu'),
('Windows'),
('macOS'),
('Nginx'),
('Apache'),
('Redis'),
('RabbitMQ'),
('Kafka'),
('ElasticSearch'),
('Tableau'),
('Power BI') ON CONFLICT (name) DO NOTHING;

COMMIT;